### ISSUE TITLE
Report issue upstream

### ISSUE THREAD

**Issue by merwok** [hakib/django-admin-lightweight-date-hierarchy#6]
Hello!  This seems like a nice package, but its starting point seems to be a clear bug in Django.
Would you mind reporting it upstream so that all django users may benefit from a fix?

In the worst case if it can’t be changed for some reasons you’d still get to clarify why this is needed with a link to upstream discussion.

**Comment by hakib** [comment]
Hey @merwok, 
I wouldent call it a bug. Django date hierarchy is implemented as a "widget" on the page that utilizes the existing filter behaviour. It actually dosen't have any other implementation in ragards to the actual filtering of the queryset.

The reason month and day are filtered using a function is because they can also stand on their own. For example, this is a valid query string to filter the 15 day of Novemeber in *all* years:

```
admin/mymodel/created__month=11&created__day=15
```

What this package does is to use the hierarchical nature of the date hierarchy to optimize the query. To use a range filter on a month lookup you must select a year. To be able to use a range filter on a day you must select a year and a month.

I think there is a place to add a custom implementation for date hierarchy in Django Admin (as it's very common) but I woulden't call it a bug in Django.

**Comment by merwok** [comment]
Thanks for the clarification!  I see now that the observed performance emerges from reasonable implementation choices, and would probably be judged not a bug by upstream.  This was not immediately obivous when reading the medium post or the readme here :)
